# cluster_config.yml - cluster configuration
__default__:
    account: primatediversity
    time: 16:00:00 # time limit for each job
    memory: 15g
    ntasks-per-node: 8

#snakemake --cluster "sbatch -A primatediversity -t 10:00:00 -N 8 --mem 16" —j 2